services:
  postgres-db:
    image: postgres:16-alpine3.20
    container_name: "P2P-Review"
    restart: unless-stopped
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "P2P_Review"
    ports:
      - "5432:5432"
  sonarqube:
    image: sonarqube:latest
    container_name: "sonar"
    restart: unless-stopped
    ports:
      - "9000:9000"
volumes:
  db_volume: